version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - RAILWAY_ENVIRONMENT=production
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery-worker
    environment:
      - RAILWAY_ENVIRONMENT=production
    command: celery -A app.infrastructure.celery.celery_app worker --loglevel=info
    restart: unless-stopped
    depends_on:
      - api

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.celery-beat
    environment:
      - RAILWAY_ENVIRONMENT=production
    command: celery -A app.infrastructure.celery.celery_app beat --loglevel=info
    restart: unless-stopped
    depends_on:
      - api 