"""add temp url fields

Revision ID: 002
Revises: 001
Create Date: 2024-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Adicionar novos campos na tabela temporary_files
    try:
        op.add_column('temporary_files', sa.Column('max_accesses', sa.Integer(), nullable=True))
    except Exception as e:
        if 'already exists' in str(e) or 'duplicate column' in str(e):
            pass
        else:
            raise
    try:
        op.add_column('temporary_files', sa.Column('custom_filename', sa.String(length=255), nullable=True))
    except Exception as e:
        if 'already exists' in str(e) or 'duplicate column' in str(e):
            pass
        else:
            raise
    try:
        op.create_index('idx_temp_files_url', 'temporary_files', ['temporary_url'], unique=False)
    except Exception as e:
        if 'already exists' in str(e) or 'duplicate' in str(e):
            pass
        else:
            raise
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remover índice
    op.drop_index('idx_temp_files_url', table_name='temporary_files')
    
    # Remover colunas
    op.drop_column('temporary_files', 'custom_filename')
    op.drop_column('temporary_files', 'max_accesses')
    
    # ### end Alembic commands ### 