"""Add download_logs table

Revision ID: 003
Revises: 002
Create Date: 2024-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade():
    try:
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('download_logs',
            sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('download_id', postgresql.UUID(as_uuid=True), nullable=True),
            sa.Column('user_id', sa.String(length=255), nullable=True),
            sa.Column('session_id', sa.String(length=255), nullable=True),
            sa.Column('video_url', sa.Text(), nullable=False),
            sa.Column('video_title', sa.String(length=500), nullable=False),
            sa.Column('video_duration', sa.Integer(), nullable=True),
            sa.Column('video_size', sa.BigInteger(), nullable=True),
            sa.Column('video_format', sa.String(length=50), nullable=False),
            sa.Column('video_quality', sa.String(length=50), nullable=False),
            sa.Column('start_time', sa.DateTime(), nullable=True),
            sa.Column('end_time', sa.DateTime(), nullable=True),
            sa.Column('download_duration', sa.Float(), nullable=True),
            sa.Column('download_speed', sa.Float(), nullable=True),
            sa.Column('file_size_downloaded', sa.BigInteger(), nullable=True),
            sa.Column('progress_percentage', sa.Float(), nullable=True),
            sa.Column('status', sa.String(length=50), nullable=False),
            sa.Column('error_message', sa.Text(), nullable=True),
            sa.Column('error_code', sa.String(length=100), nullable=True),
            sa.Column('retry_count', sa.Integer(), nullable=True),
            sa.Column('ip_address', sa.String(length=45), nullable=True),
            sa.Column('user_agent', sa.Text(), nullable=True),
            sa.Column('request_headers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
            sa.Column('response_headers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
            sa.Column('download_path', sa.String(length=500), nullable=True),
            sa.Column('output_format', sa.String(length=50), nullable=True),
            sa.Column('quality_preference', sa.String(length=50), nullable=True),
            sa.Column('google_drive_uploaded', sa.Boolean(), nullable=True),
            sa.Column('google_drive_file_id', sa.String(length=255), nullable=True),
            sa.Column('google_drive_folder_id', sa.String(length=255), nullable=True),
            sa.Column('temporary_url_created', sa.Boolean(), nullable=True),
            sa.Column('temporary_url_id', postgresql.UUID(as_uuid=True), nullable=True),
            sa.Column('temporary_url_access_count', sa.Integer(), nullable=True),
            sa.Column('memory_usage', sa.Float(), nullable=True),
            sa.Column('cpu_usage', sa.Float(), nullable=True),
            sa.Column('disk_usage', sa.Float(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['download_id'], ['downloads.id'], ),
            sa.ForeignKeyConstraint(['temporary_url_id'], ['temporary_files.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_download_logs_created_at'), 'download_logs', ['created_at'], unique=False)
        op.create_index(op.f('ix_download_logs_status'), 'download_logs', ['status'], unique=False)
        op.create_index(op.f('ix_download_logs_user_id'), 'download_logs', ['user_id'], unique=False)
        # ### end Alembic commands ###
    except Exception as e:
        if 'already exists' in str(e):
            pass
        else:
            raise


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_logs_user_id'), table_name='download_logs')
    op.drop_index(op.f('ix_download_logs_status'), table_name='download_logs')
    op.drop_index(op.f('ix_download_logs_created_at'), table_name='download_logs')
    op.drop_table('download_logs')
    # ### end Alembic commands ### 