"""Add storage_type to downloads table

Revision ID: 005
Revises: 004
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloads', sa.Column('storage_type', sa.String(length=20), nullable=True, server_default='temporary'))
    op.create_index(op.f('ix_downloads_storage_type'), 'downloads', ['storage_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_downloads_storage_type'), table_name='downloads')
    op.drop_column('downloads', 'storage_type')
    # ### end Alembic commands ### 